### ISSUE TITLE
Login is not working for the new users and for superuser its working but not redirect to the profile page

### ISSUE THREAD

**Issue by binayalenka** [CakeDC/users#323] opened 2016-03-17 14:32 UTC
I have used Cake 3.2.5 version and installed this plugin through composer
Everything working fines but after new user login is not working says there are too many loops.
but super is able to login nut not redirect to the profile page.

**Comment by thinkingmedia** [comment] 2016-03-17 15:22
I recommend that you verify that your `Users.SimpleRbac.permissions` is configured correctly.

**Comment by steinkel** [comment] 2016-03-20 16:37
Please @binayalenka check if the profile page is allowed for the role of the user just logged in, this looks like a problem with your application defined permission rules. Thanks,

**Comment by mferak** [comment] 2016-03-21 11:37
Hi, I have the same problem: lots of redirects after logging in, which results in a redirect loop browser error.

I am not sure where and how to setup the SimpleRbac permissions for the profile page? And why the profile page, does a successful login redirect to the profile page? This isn't mentioned anywhere in the documentation.

Also, if I try to set up my permissions.php with any permissions (and I'm almost certain I'm doing it by the book), I am no longer able to log out!

Thanks for any heads up!

**Comment by steinkel** [comment] 2016-03-21 11:44
Please paste or bin your current configuration to check if it's a problem with a missing permission.

**Comment by mferak** [comment] 2016-03-21 11:49
users.php:
`<?php

return [
  'Users.Social.login' => true,
  'Users.table' => 'Users',
  'OAuth.providers.facebook.options.clientId' => '123',
  'OAuth.providers.facebook.options.clientSecret' => '321',
  'reCaptcha.key' => 'XYZ
];`

permissions.php:
`<?php

return [
  'Users.SimpleRbac.permissions' => [
    [
      'role' => 'user',
      'controller' => 'Gifs',
      'action' => ['view']
    ],
    [
        'role' => 'user',
        'controller' => 'Gifs',
        'action' => ['edit','delete'],
        'owner' => new \CakeDC\Users\Auth\Rules\Owner(),
    ]
  ]
];
`

**Comment by steinkel** [comment] 2016-03-21 11:59
@mferak check https://github.com/CakeDC/users/blob/master/Docs/Documentation/SimpleRbacAuthorize.md

And add a rule to allow your users access the profile page. Keep in mind all pages are restricted unless you define a rule to match them.

Example

```php
        //allow profile page, NOTE change the route to match your profile page location
        [
            'role' => 'user',
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => ['profile'],
        ],
        //allow logout
        [
            'role' => 'user',
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => ['logout'],
        ],
```

**Comment by mferak** [comment] 2016-03-21 12:09
OK I'm now able to log out, thanks!

I am not sure I should write this down here, or start a new Issue, however I'm still encountering these problems:

- Logging in using Facebook still produces a redirect loop 
- After I log out I get an alert saying "You are not authorized to access that location." - after that I try to log back in, I get "You've successfully logged out", and I need to log in once again to finally get logged in.

**Comment by steinkel** [comment] 2016-03-21 12:12
You could try this:
* add this rule for DEBUGGING
```php
        [
            'role' => 'user',
            'controller' => '*',
            'action' => '*',
        ],
```
And check if login with facebook works, if it works, it's a problem with your rules definition, you'll need to add specific rules to cover all your protected pages.

Thanks,

**Comment by mferak** [comment] 2016-03-21 12:22
Thanks. Unfortunately, that didn't change anything.

To clarify, loggin in with facebook WORKS, it just ends up in a redirect loop. When I go back to let's say the homepage, I am logged in. 

The issue with logging out seems unrelated.

**Comment by steinkel** [comment] 2016-03-21 12:25
What's the url of the page causing the redirect loop?

**Comment by mferak** [comment] 2016-03-21 12:31
It's redirecting between '/' and '/login'

**Comment by steinkel** [comment] 2016-03-21 12:36
Login will be allowed if it's configured as the `Auth.loginAction` so you'll need to add a rule to allow the '/' page...

**Comment by mferak** [comment] 2016-03-21 12:41
That's what I meant I did (controller = Pages, action = display). 

Could it be that /auth/facebook is not allowed? 'redirectUri' => Router::url('/auth/facebook', true)

**Comment by steinkel** [comment] 2016-03-21 12:51
That should not be an issue, could you paste your access.log trace to check which page is being requested when the redirect loop happens?

**Comment by mferak** [comment] 2016-03-21 12:57
Unfortunately there's no access.log populated.

Thanks for your patience... :+1:

**Comment by steinkel** [comment] 2016-03-21 13:00
then log it to debug.log? you could do that from AppController's beforeFilter...

**Comment by mferak** [comment] 2016-03-21 13:01
That's what I did when you first asked which pages redirect in the loop. All I got was that the redirects were between '/' and 'login'

**Comment by mferak** [comment] 2016-03-21 13:03
My app is basically empty right now, there aren't any pages except for the '/' page (which I described above), and the cakedc users plugin's pages.

**Comment by steinkel** [comment] 2016-03-21 13:04
What's the route configured for '/'?

**Comment by steinkel** [comment] 2016-03-21 13:04
Are you loading the plugin using 'bootstrap' => true right?

**Comment by mferak** [comment] 2016-03-21 13:05
$routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

I have this set up in my permissions:

`    [
      'role' => 'user',
      'controller' => 'Pages',
      'action' => ['display'],
    ],`

**Comment by mferak** [comment] 2016-03-21 13:07
Yes, here's all my bootstrap init:

<pre>
Configure::write('Users.config', ['users']);
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Auth.authenticate.Form.fields.username', 'email');

Configure::delete('OAuth.providers.instagram');
Configure::delete('OAuth.providers.twitter');
Configure::delete('OAuth.providers.linkedIn');
Configure::delete('OAuth.providers.google');
</pre>

**Comment by steinkel** [comment] 2016-03-21 13:07
that's weird... if your app is empty, could you zip it to test it locally or submit the specific files to test them locally? I could take a look later today

**Comment by mferak** [comment] 2016-03-21 13:22
I'm doing a fresh install to see if anything I did in the process might have affected this.

Also, COULD it be I'm working on a virtual domain on localhost, and that there might be something fishy about facebook's return URL?

**Comment by steinkel** [comment] 2016-03-21 13:24
No, I've used a local virtualhost for testing all the Oauth providers successfully, Thanks.

**Comment by mferak** [comment] 2016-03-21 13:42
Well unfortunately, doing a fresh install and following all the steps, I got to a point where registration nor socialLogin doesn't work and I get - Unknown method "register" or Unknown method "socialLogin"

**Comment by mferak** [comment] 2016-03-21 13:49
Here's something I noticed.
The redirect loop occurs in Safari on a Mac.

In Chrome and Firefox the redirects are broken somehow by a page with URL /#_=_

**Comment by mferak** [comment] 2016-03-21 14:02
However, to confirm the redirect look does happen in all browsers, just that Safari "exits" it sooner than Chrome/Firefox, see this screenshot where you can notice this many alerts.

[https://www.dropbox.com/s/wxfo2s1escypsmm/Screenshot%202016-03-21%2015.00.48.png?dl=0](url)

**Comment by steinkel** [comment] 2016-03-21 14:04
Interesting, could you delete your session cookie and login again? Or ensure you are logged out before login again?

**Comment by mferak** [comment] 2016-03-21 14:14
Yes I did that as I tried to log in with various browsers, each was cache-free and cookie-free.

**Comment by steinkel** [comment] 2016-03-21 14:19
Ok, it's going to be hard to debug this way then, possibly something else happening in your webserver configuration. could you share your current project configuration (removing the secret keys etc.)?

**Comment by mferak** [comment] 2016-03-21 14:22
It's really just an empty project with the basic settings. 

Here is a ZIP with all the files. Obviously, you'll need to edit app.php and users.php configs; and run the migrations.

https://www.dropbox.com/s/jj7ddpuu9euhqzz/web.zip?dl=0

**Comment by steinkel** [comment] 2016-03-21 14:25
Thanks, I'll take a look and let you know.

**Comment by mferak** [comment] 2016-03-21 16:16
Here's an update:

If I initialise the FB login from any other subpage but /login, everything works fine, no redirect looping occurs.

**Comment by steinkel** [comment] 2016-03-21 16:41
Ah, that makes sense, we could introduce a condition check to detect you are trying to redirect back to login page "again". I'll close this ticket as resolved, please add a new one with the specific use case when the redirect loop happens, makes sense?

**Closed by steinkel** 2016-03-21 16:41 UTC
Labels: bug, works for me

**Comment by kwalski** [comment] 2016-04-05 00:04
@mferak did you have it working for you? I am having the same problem where the facebook authentication is returning /#_=_ and google authentication is returning to /login# 
I am new to cakephp and cakedc/users so still getting head around the basics and I beg your pardon if I missed something obvious in the discussion above.

**Comment by kwalski** [comment] 2016-04-06 00:10
Please help me to understand how it is supposed to work.
I want my app users to be authenticated using Google and Facebook.
I have tried to configure api keys in bootstrap, and also in app/config/users.php

When I access ` http://localhost:8765/users/ ` I get redirected to login screen with options to register or login using Google or Facebook.

When I click on "Login with Google" or "Login with Facebook" links on the app/login page it takes me to the respective social media sites for authentication. 
After authentication, I am redirected to the app with url ` /#_=_ ` in case of facebook and `/login#` in case of google. 

**Where is the redirection to these paths configured?** In LoginTrait I can see `$url = $this->Auth->redirectUrl(); `however, I am confused why this is not taking to ` http://localhost:8765/users/ ` as that's where I initiated the login?

I have tried with the all permissions as suggested by @steinkel however it has not changed anything
```
      [
            'role' => 'user',
            'controller' => '*',
            'action' => '*',
        ],
```

**Comment by steinkel** [comment] 2016-04-06 09:21
Hi @kwalski , first please don't use localhost, as Facebook will not allow you to create the redirect path to localhost, you'll need to configure a virtualhost to let Facebook work properly.

Then set the right auth url in your Facebook/Google app example (FB): `http://yoursite.dev/auth/facebook`

Follow the documentation https://github.com/CakeDC/users/blob/master/Docs/Documentation/Installation.md and it will work without other customizations.

Thanks,

**Comment by joseccantunes** [comment] 2016-06-03 23:58
Is this working on cakephp 3.2?
I have the same issue, with a fresh cakephp project, I keep getting /#_=_ and `You are not authorized to access that location.`
I've follow the documentation, this issue, links and nothing.

**Comment by steinkel** [comment] 2016-07-01 11:14
@joseccantunes could you please provide some more insight about your issue like posting your current configuration, permissions, etc?

Thanks,

**Comment by tgoeminne** [comment] 2016-11-30 17:53
It's not working, I get the same errors

acebook authentication is returning /#_=_ and google authentication is returning to /login#

The documentation is very confusing...

**Comment by steinkel** [comment] 2016-12-05 13:55
@tgoeminne could you please provide some way to reproduce the issue, bin your configuration and related classes so I could take a look? Please open a new ticket for your issue, thanks!

**Comment by cordelialoo** [comment] 2016-12-11 06:37
I can login using safari through iPad, but when logout it show cookiecryptTrait.php line 132 error. It works well in windows and android.

**Comment by Amit619** [comment] 2017-01-03 05:38
Does anyone found the soluation for login with google issue which redirect you to /login#. Any idea??

**Comment by Amit619** [comment] 2017-01-03 05:39
Does anyone found the soluation for login with google issue which redirect you to /login#. Any idea??

**Comment by tgoeminne** [comment] 2017-01-10 13:40
No, I have not found it, could it be it have something to do with server settings? I am using google compute with the bitnami cakephp package. I assume it is something with server settings causing a 302 code??? Otherwise I have no idea...

**Comment by tgoeminne** [comment] 2017-01-10 14:04
Actually I did find the problem https://github.com/CakeDC/users/issues/464 see my last post.

The problem I had is with the users.php config file that is not working as intended, when I set it directly into bootstrap.php it is working now.

**Comment by steinkel** [comment] 2017-01-10 15:09
Thank you for updating with the status here

**Comment by datnguyenthang** [comment] 2017-10-21 08:09
Although User record have been create in users table, but all way return to # and #_=_ when login by google and facebook. 
Debug: 
2017-10-21 07:51:45 Debug: Cannot evaluate permission when 'controller' and/or 'action' keys are absent
