### ISSUE TITLE
Social login using facebook and google failed

### ISSUE THREAD

**Issue by fin-k** [CakeDC/users#568] opened 2017-06-23 11:42 UTC
Help me. 

I tested cakedc with facebook login, but I got error "you're not authorized to access that location".

I use this configuration on bootstrap:
```
Plugin::load('CakeDC/Users', ['routes' => true, 'bootstrap' => true]);
Configure::write('Users.Social.login', true);
Configure::write('OAuth.providers.facebook.options.graphApiVersion', 'v2.8');
Configure::write('OAuth.providers.facebook.options.clientId', 'xxx');
Configure::write('OAuth.providers.facebook.options.clientSecret', 'xxx');
```

On permission.php:
```
return [
    'Users.SimpleRbac.permissions' => [
        [
            'role' => 'user',
            'controller' => '*',
            'action' => '*',
        ],
    ]];
```
I put this on facebook oauth redirection uri:

> http://localhost:8765/auth/facebook, http://localhost:8765/, http://localhost/test/facebook

The link that shows the error is this : http://localhost:8765/login?redirect=%2Fauth%2Ffacebook%3Fcode%3DAQC1132zxaX7NCAaGboY-TIlpTmZGQUq7CFegrbmfKHYLkIiirtV-G5Pvbq-TST5trAmlqNSPWbWfR8aFJeI9ipNWV_aM-DDZCASOzcdeFbt6IEkXv1VyXM9UHB9J4a9mXc9Dtu16WlqJNlnFpB4r5PPjslMW29Xao6eKN8iJWtLL0Nt5K70dGMAOBY5EhQWhfbApSAU7wzoHiptmGOhnU7_RQdkRs48ssautlSHo1y3V4YblgAHJYwbbaomT2IIp-d7hDmTzlx5eST-3yFkpru7r65onJfTxhV3VBQH_GF6KeR30X5S6myacS0TUvgsZTUkwRFQMztGDzIuD29ag2JJ%26state%3D7a590307e1af3ee25dae323c1fdcc4a5#_=_

I also tested login with google, but the same error occured.

**Comment by marcelonnunes** [comment] 2017-06-29 00:43
I also had this problem.

In my case, I had to correct the "redirectUri" URL of the configuration file "users.php"

My url: http: // localhost / my_app

In /vendor/cakedc/users/config/users.php

Before:
'RedirectUri' => Router :: fullBaseUrl (). '/ Auth / facebook'

After:
'RedirectUri' => Router :: fullBaseUrl (). '/ my_app / auth / facebook',

The problem seems to be with fullBaseUrl ()

/vendor/cakedc/users/config/users.php
```
    'OAuth' => [
        'path' => ['plugin' => 'CakeDC/Users', 'controller' => 'Users', 'action' => 'socialLogin', 'prefix' => null],
        'providers' => [
            'facebook' => [
                'className' => 'League\OAuth2\Client\Provider\Facebook',
                'options' => [
                    'graphApiVersion' => 'v2.5',
                    'redirectUri' => Router::fullBaseUrl() . '/**your_app**/auth/facebook',
                ]
            ],
```

**Comment by ajibarra** [comment] 2017-06-29 18:35
Facebook login is not supposed to work with localhost domain. Using a virtual host is a good idea. 

Thanks for your comment @marcelonnunes .

Closing this issue since it is caused by user config

**Closed by ajibarra** 2017-06-29 18:35 UTC
Labels: bug

**Comment by blackstar-7** [comment] 2017-12-12 14:15
hi @ajibarra  i have the  same problem 
it was working fine but when i move to **3.5.*** i got error "you're not authorized to access that location".
facebook login worked fine on localhost domaine 
my facebook settings ; 
http://localhost:8765/auth/facebook, http://localhost:8765/, 
its been a week now and i cant figured it out !
